---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-client
spec:
  selector:
    matchLabels:
      run: eureka-client
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-client
    spec:
      containers:
        - name: eureka-client
          image: alessandrocavaglia/eureka-client
          ports:
            - containerPort: 8763